// "/My Website/public/Images"

const EachProjectData = [
    {
        id: 1,
        link: `https://millionaire-quiz-app-ten.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Millionaire-Quiz-App`,
        imgSrc: "/Images/project-1.png",
        title: "MILLIONAIRE QUIZ APP",
        language : `REACT AND CSS`,
        projectInfoText: 
        `INTERMADIATE LEVEL REACT PROJECT BECAUSE THERE ARE LOT'S OF SMALL BUT TOO MANY FUNTIONALLITY, WHERE  EACH AND EVERY PROJECT 
        CONNECTS THE WHOLE APP. I MADE SOME LOCAL API OF Q&A.  AS YOU CAN SEE GAME WILL START WHEN YOU CLICK THE BUTTON.
         I USE GOOGLE EVERY TIME HONESTLY. AND TO GET KNOW DIFF HOOKS I USE YOUTUBE TOO. IT TOOK ME 1/5 WEEK TO COMPLETE. PLEASE FREE TO USE`,
        projectInfoText1: `API CONCEPT, SETTIME OUT, USEEFFECT, USESTATE || NOT RESPONSIVE FULLY.`,
        backgroundImage: "linear-gradient(to top left, #004e9272,#000428f3)",
    },
    {
        id: 2,
        link: `eachproject/`,
        imgSrc: "/Images/project_img/My Website.png",
        title: "MY WEBSITE",
        language : `REACT ROUTER DOM, REACT AND ONLY CSS`,
        projectInfoText: 
        `THIS IS AMAZING, USING FULLY CSS, REACT, JAVASCRIPT. ONLY CSS HERE WITH RESPONSIVE. REALLY BIG PROJECT FOR ME. IT TOOK MORE THEN
         3 WEEKS TO COMPLETE. IF YOU CHECK THE SOURCE ON GITHUB YOU WILL FOUND I USE LOCAL API TO FETCH DATA. USEPARAMS, USESTATE. TO 
          CONNECT WITH EACH CLICK TO EACH ID FROM URL TO MATCH. THAT IS REAL CHALLENGE FOR ME BUT AS I LEARN IT IS NOT THAT HARD.
           ONE OF THE HARDEST HERE IS TO BUILD PROJECT PAGE LOGIC, CHECK IT...`,
        projectInfoText1: `LOCAL API, SUPER CSS RESPONSIVE,REACT.JS || ABOUT PAGE,BACK BUTTON LOGIC, DIDN'T STORE EVERYTHING IN STATE`,
        backgroundImage: "linear-gradient(to top left,  #000000ad,  #ffffff )",
    },
    {
        id: 3,
        link: `https://to-do-list-nine-beta-41.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/To-Do-List`,
        imgSrc: "/Images/project_img/To Do List.png",
        title: "TO DO LIST",
        language : `JAVASCRIPT AND ONLY CSS`,
        projectInfoText: 
        `THIS IS JAVASCRIPT PROJECT.I KNOW EVERYONE IS DOING THIS BUT BY DOING THIS THEE LOT'S OF CONCEPTS ARE GET VERY 
        CLEAR. I SPEND EQUAL TIME ON CSS AS MUCH AS JAVASCIPT. FREE TO CHECK ON GITGUB. IF YOU DON'T LIKE IT THEN TELL ME`,
        projectInfoText1: `RESPONSIVE, LOVELY LOOKING, SIMPLE LOGIC  ||  INTERMADIATE LOGIC, LITTLE REAPETED`,
        backgroundImage: "linear-gradient(to top left,  #004e92c9,  #ffffff )",
    },
    {
        id: 4,
        link: `https://digital-clock-rho-blue.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Digital-Clock`,
        imgSrc: "/Images/project_img/Digital Clock .png",
        title: "DIGITAL CLOCK",
        language : `JAVASCRIPT AND ONLY CSS`,
        projectInfoText: `THIS IS ACTUALLY ONE OF MY FIRST JAVASCRIPT PROJECTS. NOT BIG BUT CALCULATIVE. THERE IS NO INTERACTION BUT
        BUT CHANGE IN DOM IS VERY PERFECT IN MY GUESS THOUGH. IF IT'S NOT THEN TELL ME. `,
        projectInfoText1: `SIMPLE LOGIC, DOM MANUPULATION  ||  LITTLE CONFUSING`,
        backgroundImage: "linear-gradient(to top left, #5154a3,#cecfcfd8)",
    },
    {
        id: 5,
        link: `https://story-telling-app-js.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/StoryTelling-App-Js`,
        imgSrc: "/Images/project_img/Story Telling.png",
        title: "STORY TELLING",
        description: "DESCRIPTION IS GOOD",
        language : `JAVASCRIPT AND ONLY CSS`,
        projectInfoText: `LIKE 30% CSS BUT LIGIC IS BIT COMPLICATED. YOU SEE EACH CLICK SHOULD RENDER ME TO EXACT PLACE WHERE USER LEVE
        THAT BEFORE IS COMPLEX. BUT HEYY, I AM REALLY ASKING YOU TO CLICK TO SEE YOURSELF. YOU WOULD APPRITIATE ME. `,
        projectInfoText1: `LIKE VERY LOW CSS, NOT RESPONSIVE  ||  FUN TO KNOW WHAT WILL BE END `,
        backgroundImage: "linear-gradient(to top left,  #ffffff6c,  #ffffff )",
    },
    {
        id: 6,
        link: `https://disney-clone-tan-five.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Disney-Clone`,
        imgSrc: "/Images/project_img/rt-1.png",
        title: "DISNEY CLONE",
        language : `REACT ROUTER DOM, REACT, STYLED COMPONENTS, REDUX, FIREBASE`,
        projectInfoText: `THIS IS UPCOMMING PROJECT. I WILL DO IT WHEN I LEARN ABOUT REDUX MORE. REDUX IS BEST WAY TO HANDLE STATE
        IN REACT AND OBVIOUSLY CLONE LIKE THIS IS VERY HARD TO MAINTAIN. ACTUALLY REDUX IS ONLY CAUSE STYLED COMPONENT AND FIREBASE
        AS BACKEND IS MAKING PERFECT. SO I WILL BACK SOON AS POSSIBLE`,
        projectInfoText1: `REACT ,REDUX, RESPONSIVE,FIREBASE  ||  NOT COMPLETED YET `,
        backgroundImage: "linear-gradient(to top left,   #1e3b72b6, #070e24 )",
    },
    {
        id: 7,
        link: `https://toggle-theme-js.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Toggle-Theme-JS`,
        imgSrc: "/Images/project_img/js-5.png",
        title: "TOGGLE THEME APP",
        language : `JAVASCRIPT AND ONLY CSS`,
        projectInfoText: `PLEASE DON'T JUDGE AT FIRST. IT NOT JUST TOGGLING, I MADE SOME API CALL TO RENDER DATA ON THE SCREEN 
        BY USING PROMISES. FETCH DATA THEN SHOW IT ON SCEEN AND TOGGLE IT. PROJECT IT SELF IS NOT COMPLICATED BUT I MADE IT THOUGH`,
        projectInfoText1: `SIMPLE CONCEPT, API CALL  ||  WHEN TOGGLE IT SHOULD ALSO TOGGLE DATA `,
        backgroundImage: "linear-gradient(to top left,  #d4d4d4b6, #ffbaba )",
    },
    {
        id: 8,
        // link: ``,
        source : `https://github.com/Yashvant-Mainkar/Search-Movies-Api-React`,
        imgSrc: "/Images/project_img/react-2.png",
        title: "REACT API MOVIE APP",
        language : `REACT AND ONLY CSS`,
        projectInfoText: `GO AND SEARCH SOME MOVIES. SIMPLE FETCH DATA API PROJECT. BUT FINDING ORIGINAL URL AND FETCHING WITHOUT IS REALLY A STRUGGLE. BUT SOLVING 
        PROMISES IS WON'T BECAUSE OF JAVASCRIPT. CSS IS REAL MINISTER HERE BUT USEEFFECT ALSO DID WORK `,
        projectInfoText1: `API CALL, WORK OF REACT COMPONENT  ||  IT COULD GO MORE DEEPER `,
        backgroundImage: "linear-gradient(to top left,   #ffffff,#00000073 )",
    },
    {
        id: 9,
        link: `https://multipplication-app.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Multipplication-App`,
        imgSrc: "/Images/project_img/js-4.png",
        title: "MULTIPLICATION APP",
        language : `JAVASCRIPT`,
        projectInfoText: `YOU'RE WELCOME TO JUDGE ME BECAUSE THIS IS ONE OF MY FIRST JS PROJECT. BUT STILL IT'S BIT HARDER. EVERYTIME
        YOU WIN OR LOSE YOU HAVE TO INCREASE OR DECREASE SCORE. SO FOR ME I STILL LOVE THIS PROJECT.`,
        projectInfoText1: `SCORE LOGIC  ||  SIMPLE `,
        backgroundImage: "linear-gradient(to top left,  #fba9b7, #fb889b86 )",
    },
    {
        id: 10,
        link: `https://heart-animation-one.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Heart-Animation`,
        imgSrc: "/Images/project_img/js-6.png",
        title: "CURSOR HEART ANIMATION WEBSITE",
        description: "CURSOR HEART ANIMATION WEBSITE",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `HEART ANIMATION JAVASCRIPT PROJECT. CSS IS KING HERE. I GET THE IDEA FROM YOUTUBE.FIRST I BUILD WHILE WATCHING
        THEN I DID IT BY MYSELF. YOU REALLY LOVE IT. THE CURSOR IS KING TOO. CLICK ON BUTTON AND PLAY `,
        projectInfoText1: `WINDOW CURSOR POSITIONING ||  NOT COMPLETE MY PROJECT `,
        backgroundImage: "linear-gradient(to top left,  rgba(30,28,28,1) 40%, rgba(235,235,235,1) )",
    },
    {
        id: 11,
        link: `https://counter-app-six-jet.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Counter-App`,
        imgSrc: "/Images/project_img/js-8.png",
        title: "COUNTER BUTTON",
        language : `JAVASCRIPT`,
        projectInfoText: `MY FIRST JAVASCRIPT PROJECT. SIMPLE BUT INITIAL KNOWLEDGE FOR THIS IS ALSO VERY OVERWHELMING BACK TIME. 
        CHECK GITHUB LINK. `,
        projectInfoText1: `SIMPLE ||  SIMPLE `,
        backgroundImage: "linear-gradient(to top left,  rgba(0,0,0,1) 19%, rgba(235,235,235,1) )",
    },
    {
        id: 12,
        // link: ``,
        // source : ``,
        imgSrc: "/Images/project_img/rt-2.png",
        title: "STORYTELLING REACT WEB APP",
        description: "",
        language : `REACT ROUTER DOM, REACT.JS, LOCAL API AND CSS`,
        projectInfoText: `I MADE FIRST JAVASCRIPT PROJECT OF THIS THEN I GET THE IDEA TO DO THIS. I HAVEN'T COMPLETED YET BUT SOON YOU 
        WILL LOVE IT. I REALLY HAVE VERY FANTESTIC STORY IN MY MIND. IT JUST TIME TO LEARN REDUX AND THEN... `,
        projectInfoText1: `VERY INTRESTING STORY ||  NOT COMPLETE YET THIS PROJECT `,
        backgroundImage: "linear-gradient(to top left,  #000000ad,  #ffffff )",
    },
    {
        id: 13,
        // link: ``,
        // source : ``,
        imgSrc: "/Images/project_img/rt-3.png",
        title: "SOCIAL MEDIA APP",
        language : `REACT ROUTER DOM, REACT.JS, FIREBASE AND CSS`,
        projectInfoText: `THIS GONNA BE WHOLESOME APP TO LEARN MORE ABOUT REACT AND REDUX. I AM SO EXITED TO SHOW YOU WHAT I DID || HOW 
        I COMPLETED THIS. ll'be BACK...`,
        projectInfoText1: `VERY INTRESTING APP, REAL, REAL ||  NOT COMPLETE YET THIS PROJECT `,
        backgroundImage: "linear-gradient(to top left,  rgba(26,55,160,1) 19%, rgba(245,241,241,1) )",
    },
    {
        id: 14,
        link: `https://weather-app-js-eta.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Weather-App-Js`,
        imgSrc: "/Images/project_img/js-9.png",
        title: "JAVASCRIPT WEATHER APP",
        language : `JAVASCRIPT, ONLINE API, CSS`,
        projectInfoText: `THIS WILL BE NOT TOO HIGH TIP PROJECT. I GUESS AFTER SOME TIME THE FETCH URL IS NOT BE ABLE TO FETCH 
        IT PERFECTLY. BUT WHILE I AM MAKING THIS WEBSITE THIS IS AMAZING PROJECT. CHECH GITHUB LINK FOR MERE`,
        projectInfoText1: `PERFECT LOGIC TO FETCH DATA ||  MESSED UP FETCH URL `,
        backgroundImage: "linear-gradient(to top left,  rgba(30,28,28,1) 40%, rgba(235,235,235,1) )",
    },
    {
        id: 15,
        link: `https://image-slider-js-tau.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/ImageSlider-JS`,
        imgSrc: "/Images/project_img/js-10.png",
        title: "IMAGE SLIDER",
        language : `JAVASCRIPT`,
        projectInfoText: `SIMPLE BUT LOGICAL PROJECT. I DID MAKE 3 MORE BUT ATLAST, I CAME TO THIS LOGIC. I REALLY LIKE DOING THIS `,
        projectInfoText1: `AFTER IMAGE FINISHED, BUTTON VANISHED  ||  I COULD DO MRE `,
        backgroundImage: "linear-gradient(to top left,  #42892d86, #ffffff )",
    },
    {
        id: 16,
        link: `https://dictionary-app-by-js.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Dictionary-App-by-JS`,
        imgSrc: "/Images/project_img/js-11.png",
        title: "DICTIONARY WORD FINDER APP",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `DATA FETCHING IN JAVASCRIPT IS PRETTY GOOD CHALLENGE. I FETCH THE DATA FROM ONLNE AND THEN USE IT IN.
        NOT GOOD CSS STYLEING BUT JAVASCRIPT IS... OK YOU CAN TELL ME.`,
        projectInfoText1: `ACTUALLY WORK  ||  MORE CSS, MORE CLEARITY `,
        backgroundImage: "linear-gradient(to top left,  #07914e,#ffffff )",
    },
    {
        id: 17,
        link: `https://js-calculator-2.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/JS-Calculator-2`,
        imgSrc: "/Images/project_img/js-12.png",
        title: "JAVASCRIPT CALCULATOR",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `SIMPLE UNIVERSAL JS PROJECT AND HERE I AM. I ALSO DID IT WITH PERFECTION. CHECK THE GITHUB LINK AND SEE IT YOUSELF.`,
        projectInfoText1: `ACTUALLY WORK  ||  I SHOULD STORE PREVIOUS HISTORY TOO`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#342f2f )",
    },
    // 
    {
        id: 18,
        link: `https://e-commerce-website-neon-eight.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/E-Commerce-Website`,
        imgSrc: "/Images/project_img/rt-5.png",
        title: "E-COMMERCE WEBSITE (REACT.JS)",
        language : `REACT AND CSS`,
        projectInfoText: `IT TOOK ME 3 MONTHS TO COMPLETE THIS PROJECT. I GOOGLE LIKE CHILD. I AM SO EXCITED TO SHOW THIS PROJECT TO EVRYONE. AI AND OTHER TOOLS LIKE FIGMA AND GITHUB VERY HELP ME `,
        projectInfoText1: `EVRYTHING... I MEAN EVRYTHING IS GOOD  ||  I FORGOT TO ADD ONE FEATURE (SEARCH INPUT FUCNTION)`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#0fa704 )",
    },
    {
        id: 19,
        link: `https://bill-divider-phi.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Bill-Divider`,
        imgSrc: "/Images/project_img/js-13.png",
        title: "JAVASCRIPT BILL DIVIDER",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `I ASK CHAT-GPT FOR UNIQUE JAVASCRIP PROJECT NAME AND IT'S CAME UP WITH THIS (BILL DIVIDER). I MYSELF VERY LIKE THIS AS JAVASCRIPT. CHECK YOURSELF`,
        projectInfoText1: `JAVASCRIPT AND CSS || VERY PERFECLTY EXICUTED`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#342f2f )",
    },
    {
        id: 20,
        link: `https://food-delivery-app-black-sigma.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Food-Delivery-App`,
        imgSrc: "/Images/project_img/js14.png",
        title: "FOOD DELIVERY APP",
        language : ` CSS`,
        projectInfoText: `MOSTLY FOCUS ON CSS AND RESPONSIVE (UI) BASE PROJECT. CHECK THE GITHUB LINK AND SEE IT YOUSELF.`,
        projectInfoText1: `VERY ATTRACTIVE DESIGN  ||  VERY LITTLE JAVASCRIPT ADDED`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#342f2f )",
    },
    {
        id: 21,
        link: `https://meme-generator-mu-mauve.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Meme-Generator`,
        imgSrc: "/Images/project_img/js-15.png",
        title: "JAVASCRIPT, API AND CSS",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `VERY GREATE PROJECT TO ACCOMPLISH YOUR API SKILLS. CHECK THE GITHUB LINK AND SEE IT YOUSELF.`,
        projectInfoText1: `PERFECLTY DONE ||  I SHOULD DO MORE FEATURES`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#342f2f )",
    },
    {
        id: 22,
        link: `https://photo-editing-app.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Photo-editing-app`,
        imgSrc: "/Images/project_img/js-16.png",
        title: "JAVASCRIPT PHOTO EDITING APP",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `VERY PERFECTLY DONE PROJECT. LOT'S OF GOOGLING & SEARCHING, CSS RESPONSIVE.IT ACTUALLY WORKS. CHECK THE GITHUB LINK AND SEE IT YOUSELF.`,
        projectInfoText1: `JAVASCRIPT LOGIC, CSS RESPONSIVE ||  I GUESS I DID VERY GOOD`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#342f2f )",
    },
    {
        id: 23,
        link: `https://task-checker-two.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Task-Checker`,
        imgSrc: "/Images/project_img/js-17.png",
        title: "TASK CHECKER",
        language : `JAVASCRIPT AND CSS`,
        projectInfoText: `LOCAL STORAGE TO STORE INPUT DATA AND "getItem" TO SHOW IT ON SCREEN. CSS RESPONSIVE 100%. I MYSELF VERY LIKE THIS PROJECT CHECK THE GITHUB LINK AND SEE IT YOUSELF.`,
        projectInfoText1: `LOCAL STORAGE, CSS RESPONSIVE, JSVASCRIPT  ||  I SHOULD STORE PREVIOUS HISTORY TOO`,
        backgroundImage: "linear-gradient(to top left,  #ffffff,#342f2f )",
    },
    {
        id: 24,
        link: `https://quote-generator-kappa-neon.vercel.app/`,
        source : `https://github.com/Yashvant-Mainkar/Quote-Generator`,
        imgSrc: "/Images/project_img/rt-6.png",
        title: "QUOTE GENERATOR",
        language : `REACT`,
        projectInfoText: `UNDERSTANDING WEB API'S AND UI RENDER. I ALSO DID IT WITH PERFECTION. CHECK THE GITHUB LINK AND SEE IT YOUSELF.`,
        projectInfoText1: `fit/api/quotes/  ||  I SHOULD DO MORE RESPONSIVE`,
        backgroundImage: "linear-gradient(to top left,  #31c5eb,#115fa3 )",
    },
    
];

export default EachProjectData;